/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppHopDongRouteImport } from './routes/_app/hop-dong'
import { Route as AppMauVanBanRouteImport } from './routes/_app/mau-van-ban'
import { Route as AppTongQuanRouteImport } from './routes/_app/tong-quan'
import { Route as AppHoSoDauThauIndexRouteImport } from './routes/_app/ho-so-dau-thau/index'
import { Route as AppHoSoDauThauDocumentIdRouteImport } from './routes/_app/ho-so-dau-thau/$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHopDongRoute = AppHopDongRouteImport.update({
  id: '/hop-dong',
  path: '/hop-dong',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMauVanBanRoute = AppMauVanBanRouteImport.update({
  id: '/mau-van-ban',
  path: '/mau-van-ban',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTongQuanRoute = AppTongQuanRouteImport.update({
  id: '/tong-quan',
  path: '/tong-quan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHoSoDauThauIndexRoute = AppHoSoDauThauIndexRouteImport.update({
  id: '/ho-so-dau-thau/',
  path: '/ho-so-dau-thau/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHoSoDauThauDocumentIdRoute =
  AppHoSoDauThauDocumentIdRouteImport.update({
    id: '/ho-so-dau-thau/$documentId',
    path: '/ho-so-dau-thau/$documentId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hop-dong': typeof AppHopDongRoute
  '/mau-van-ban': typeof AppMauVanBanRoute
  '/tong-quan': typeof AppTongQuanRoute
  '/ho-so-dau-thau/$documentId': typeof AppHoSoDauThauDocumentIdRoute
  '/ho-so-dau-thau/': typeof AppHoSoDauThauIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hop-dong': typeof AppHopDongRoute
  '/mau-van-ban': typeof AppMauVanBanRoute
  '/tong-quan': typeof AppTongQuanRoute
  '/ho-so-dau-thau/$documentId': typeof AppHoSoDauThauDocumentIdRoute
  '/ho-so-dau-thau': typeof AppHoSoDauThauIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/hop-dong': typeof AppHopDongRoute
  '/_app/mau-van-ban': typeof AppMauVanBanRoute
  '/_app/tong-quan': typeof AppTongQuanRoute
  '/_app/ho-so-dau-thau/$documentId': typeof AppHoSoDauThauDocumentIdRoute
  '/_app/ho-so-dau-thau/': typeof AppHoSoDauThauIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hop-dong'
    | '/mau-van-ban'
    | '/tong-quan'
    | '/ho-so-dau-thau/$documentId'
    | '/ho-so-dau-thau/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hop-dong'
    | '/mau-van-ban'
    | '/tong-quan'
    | '/ho-so-dau-thau/$documentId'
    | '/ho-so-dau-thau'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/hop-dong'
    | '/_app/mau-van-ban'
    | '/_app/tong-quan'
    | '/_app/ho-so-dau-thau/$documentId'
    | '/_app/ho-so-dau-thau/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hop-dong': {
      id: '/_app/hop-dong'
      path: '/hop-dong'
      fullPath: '/hop-dong'
      preLoaderRoute: typeof AppHopDongRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mau-van-ban': {
      id: '/_app/mau-van-ban'
      path: '/mau-van-ban'
      fullPath: '/mau-van-ban'
      preLoaderRoute: typeof AppMauVanBanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tong-quan': {
      id: '/_app/tong-quan'
      path: '/tong-quan'
      fullPath: '/tong-quan'
      preLoaderRoute: typeof AppTongQuanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ho-so-dau-thau/': {
      id: '/_app/ho-so-dau-thau/'
      path: '/ho-so-dau-thau'
      fullPath: '/ho-so-dau-thau/'
      preLoaderRoute: typeof AppHoSoDauThauIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ho-so-dau-thau/$documentId': {
      id: '/_app/ho-so-dau-thau/$documentId'
      path: '/ho-so-dau-thau/$documentId'
      fullPath: '/ho-so-dau-thau/$documentId'
      preLoaderRoute: typeof AppHoSoDauThauDocumentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppHopDongRoute: typeof AppHopDongRoute
  AppMauVanBanRoute: typeof AppMauVanBanRoute
  AppTongQuanRoute: typeof AppTongQuanRoute
  AppHoSoDauThauDocumentIdRoute: typeof AppHoSoDauThauDocumentIdRoute
  AppHoSoDauThauIndexRoute: typeof AppHoSoDauThauIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHopDongRoute: AppHopDongRoute,
  AppMauVanBanRoute: AppMauVanBanRoute,
  AppTongQuanRoute: AppTongQuanRoute,
  AppHoSoDauThauDocumentIdRoute: AppHoSoDauThauDocumentIdRoute,
  AppHoSoDauThauIndexRoute: AppHoSoDauThauIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
